# Generated by Django 2.0 on 2017-12-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Cargo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Persona'),
        ),
    ]
