# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0005_auto_20171229_2329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retraso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_see_all', 'Ver todos'), ('can_see_owner', 'Solo los que creo')),
                'abstract': False,
            },
        ),
    ]
