# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_retraso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retraso',
            name='proyecto',
        ),
    ]
