# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_retraso_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horaEntrada',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='entrada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
