# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_auto_20180215_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='longitud',
            field=models.FloatField(),
        ),
    ]
