# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_auto_20180216_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='horaEntrada',
            field=models.TimeField(),
        ),
    ]
