# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_auto_20180216_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='horaEntrada',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
