# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Persona')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Proyecto')),
            ],
            options={
                'permissions': (('can_see_all', 'Ver todos'), ('can_see_owner', 'Solo los que creo')),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Cargo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_see_all', 'Ver todos'), ('can_see_owner', 'Solo los que creo')),
                'abstract': False,
            },
        ),
    ]
