# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0002_contactoproyecto_proyectousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoempresa',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactoproyecto',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
