# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0004_auto_20171229_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactoproyecto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proyectousuario',
            options={},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='contactoproyecto',
            unique_together=set([('persona', 'proyecto')]),
        ),
        migrations.AlterUniqueTogether(
            name='proyectousuario',
            unique_together=set([('usuario', 'proyecto')]),
        ),
    ]
