# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0006_auto_20180221_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fechaEstadoProyecto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyectousuario',
            name='desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectousuario',
            name='hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectousuario',
            name='horas',
            field=models.FloatField(default=0),
        ),
    ]
