# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0007_auto_20180223_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigoPostal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='idProyecto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ip',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombreCalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
