# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0008_auto_20180223_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='f_Estado_proyecto_estado', to='parametrizacion.Estado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='f_P_tipo_proyecto', to='parametrizacion.Tipo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='valorAdjudicado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
