# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0009_auto_20180227_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactoproyecto',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contactoproyecto',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='contactoproyecto',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='descripcionCargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombreCalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Persona'),
        ),
        migrations.DeleteModel(
            name='ContactoProyecto',
        ),
    ]
